### PR TITLE
Fix fixture data; update algorithm.

### PR DESCRIPTION
**Pull request by jamesplease**
Nice work @mzgoddard!

Unfortunately I'm a big dummy and had the wrong fixture data for addition :astonished:  I updated the data and your algorithm.

Although I plan to use this for the date-related library I'm working on, my personal search continues for a more general solution. If you wanted to try your luck with it, restrict yourself to using these constants:

``` js
// The distance between subsequent holes (number of workdays)
var HOLE_SPACING = 5;

// The length of the hole (number of weekend days)
var HOLE_LENGTH = 2;

// The location that the whole starts at (Saturday)
var HOLE_START = 6;

// Lastly, any other number that is constant among variations of the above constants
var CONSTANTS = [ ... ];
```

### CODE REVIEW

**Comment by jamesplease** [comment]
oh oops, tests aren't passing here. Interesting. My moment-ified version is passing

**Comment by jamesplease** [comment]
gonna close. will reopen if i figure it out

**Comment by mzgoddard** [comment]
Merging in #2. Thanks @jmeas! :smile:

**Comment by jamesplease** [comment]
:)

Thank _you_! You can see the fruits of your labor [over here](https://github.com/jmeas/moment-business) ;)

**Pull request closed without merging**
